kind: pipeline
name: default

steps:
- name: test
  image: python:3.8.0-alpine3.10
  commands:
  - pip install --upgrade pip setuptools wheel
  - pip3 install -e .
  - pytest dotscience
- name: pypi_publish
  image: plugins/pypi
  when:
    event: [ tag ]
  settings:
    username: 
      from_secret: pypi_username
    password: 
      from_secret: pypi_password
- name: docker-publish
  image: plugins/docker
  when:
    event: [ push ]
  settings:
    repo: quay.io/dotmesh/dotscience-python3
    registry: quay.io
    dockerfile: Dockerfile
    auto_tag: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password